apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
 - target:
      group: azure.upbound.io
      version: v1beta1
      kind: ResourceGroup
      name: rg-myfirst
   path: resourcegroup-patch.yaml